#Config for MQTT-Server
mqtt_config:
  mqtt_server: 192.168.178.36
  mqtt_port: 1883
  mqtt_timeout: 60
  mqtt_room_topic: testroom
  mqtt_qos: 0
  mqtt_tls_enable: false
  mqtt_tls_port : 8888
  mqtt_tls_ca_cert_file: my_ca.crt
  #mqtt_tls_ca_cert_file: /etc/moquitto/ca_certs/my_ca.cert
  #for future use
  #mqtt_tls_server_cert_file : /etc/mosquitto/certs/my_server.cert
  #mqtt_tls_server_key_file : /etc/mosquitto/certs/my_server.key
  mqtt_tls_user_name: influencer
  mqtt_tls_user_pass: influenceME